import { motion } from 'framer-motion';
import {
  ArrowRight, BarChart3, BellRing, Bot, Boxes, BriefcaseBusiness, Check, CircleDollarSign,
  Clock3, FileCheck2, Gauge, HandCoins, Map, MapPinned, Network, Radar, ReceiptIndianRupee,
  Route, ShieldCheck, Smartphone, Truck, UsersRound, WalletCards, Zap,
} from 'lucide-react';
import Hero from '../components/Hero.jsx';
import FeatureCard from '../components/FeatureCard.jsx';
import SectionTitle from '../components/SectionTitle.jsx';
import Button from '../components/Button.jsx';

const fadeUp = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.16 }, transition: { duration: 0.48 } };
const platforms = [
  ['Client Dashboard', 'Live shipment tracking\nETA monitoring\nPOD visibility\nAnalytics & reports', BarChart3, 'from-blue-600 to-blue-400'],
  ['Vendor Dashboard', 'Invoice tracking\nPayment visibility\nBill discounting access\nTrip & load history', BriefcaseBusiness, 'from-emerald-600 to-emerald-400'],
  ['Driver App', 'Trip updates\nNavigation & maps\nDocument upload\nExpenses & SOS', Smartphone, 'from-amber-400 to-orange-500'],
  ['Operations Dashboard', 'Smart dispatching\nTrip management\nAlerts & analytics\nAI driven analytics', Network, 'from-violet-600 to-purple-400'],
];
const steps = [['1', 'Trip Completed', 'Your trip and POD are completed and verified.', Truck], ['2', 'Invoice Raised', 'Invoice is raised and submitted on the platform.', ReceiptIndianRupee], ['3', 'AI Verified', 'AI and risk engine verify the invoice and approve instantly.', ShieldCheck], ['4', 'Funds Released', 'Get up to 90% of invoice value credited to your account.', WalletCards]];
const aiItems = [['Predictive Maintenance', 'Predict issues before breakdowns', Gauge], ['Smart Dispatching', 'Assign right vehicle for every load', Route], ['Route Optimization', 'Reduce fuel usage & delivery time', MapPinned], ['Intelligent Alerts', 'Detect anomalies in real-time', BellRing], ['Operational Insights', 'AI recommendations for efficiency', Bot], ['Compliance Monitoring', 'Automated compliance checks', FileCheck2]];

function DashboardPreview({ dark = false }) {
  return <div className={`rounded-[20px] border p-3 shadow-xl ${dark ? 'border-white/10 bg-[#071b43]' : 'border-slate-100 bg-white'}`}>
    <div className="flex items-center gap-2"><span className="h-7 w-7 rounded-lg bg-[#0d5eff]" /><span className={`h-2 w-20 rounded-full ${dark ? 'bg-white/20' : 'bg-slate-200'}`} /><span className="ml-auto h-2 w-10 rounded-full bg-emerald-400" /></div>
    <div className="mt-3 grid grid-cols-[58px_1fr] gap-3"><div className={`rounded-lg p-2 ${dark ? 'bg-white/5' : 'bg-slate-50'}`}><i /><i /><i /><i /></div><div className="space-y-2"><div className={`h-12 rounded-lg ${dark ? 'bg-blue-400/15' : 'bg-blue-50'}`} /><div className="grid grid-cols-3 gap-2"><div className="h-10 rounded-lg bg-emerald-50" /><div className="h-10 rounded-lg bg-blue-50" /><div className="h-10 rounded-lg bg-amber-50" /></div><div className={`h-16 rounded-lg ${dark ? 'bg-white/5' : 'bg-slate-50'}`} /></div></div>
  </div>;
}

function PlatformCard({ item }) { const [title, bullets, Icon, gradient] = item; return <motion.article {...fadeUp} className="group rounded-2xl border border-slate-100 bg-white p-4 shadow-[0_10px_28px_rgba(15,23,42,.07)] transition hover:-translate-y-1"><div className={`mb-4 flex h-24 items-end rounded-xl bg-gradient-to-br ${gradient} p-3`}><Icon className="rounded-lg bg-white/90 p-1.5 text-slate-800" size={31} /></div><h3 className="text-sm font-bold text-slate-900">{title}</h3><ul className="mt-3 space-y-1.5 text-[11px] leading-4 text-slate-500">{bullets.split('\n').map((x) => <li className="flex gap-1.5" key={x}><Check size={12} className="mt-0.5 shrink-0 text-[#1260ff]" />{x}</li>)}</ul><a href="#contact" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#1260ff]">Learn more <ArrowRight size={12} /></a></motion.article>; }

function Footer() { const columns = { Platform: ['TMS', 'Fleet Management', 'Control Tower', 'Live Tracking'], Features: ['Maintenance', 'Fuel Management', 'Trip Management', 'Driver Management', 'Compliance'], Finance: ['Bill Discounting', 'Vendor Payments', 'Invoice Management'], Resources: ['Blog', 'Case Studies', 'Videos', 'Guides'], Company: ['About Us', 'Careers', 'Contact Us', 'Privacy Policy'] }; return <footer className="bg-[#041333] text-white"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><div className="grid gap-9 lg:grid-cols-[1.5fr_4fr]"><div><img src="/src/assets/logo.png" alt="Easy Lane" className="h-14 w-auto brightness-0 invert" /><p className="mt-4 max-w-52 text-xs leading-5 text-white/60">An intelligent logistics platform built to move businesses forward.</p></div><div className="grid grid-cols-2 gap-7 sm:grid-cols-5">{Object.entries(columns).map(([title, links]) => <div key={title}><h3 className="text-xs font-bold">{title}</h3><ul className="mt-3 space-y-2 text-[11px] text-white/55">{links.map((x) => <li key={x}><a href="#home" className="hover:text-white">{x}</a></li>)}</ul></div>)}</div></div><div className="mt-8 flex flex-col gap-2 border-t border-white/10 pt-4 text-[10px] text-white/45 sm:flex-row sm:justify-between"><span>© 2025 Easy Lane Logistics. All rights reserved.</span><span>Made with ♥ for the logistics world.</span></div></div></footer>; }

const Home = () => <div className="overflow-hidden bg-white text-slate-900"><Hero /><main>
  <section className="border-y border-slate-100 py-7"><p className="text-center text-xs text-slate-500">Trusted by forward-thinking businesses</p><div className="mx-auto mt-4 flex max-w-4xl flex-wrap items-center justify-center gap-x-8 gap-y-3 text-base font-extrabold italic text-slate-500 sm:text-lg"><span>▼TCI</span><span>VRL</span><span className="text-cyan-600">Gati</span><span className="text-blue-700">BLUE DART</span><span>DELHIVERY</span><span className="not-italic">Ecom<br />Express</span><span className="not-italic">mahindra<br />logistics</span><span className="text-yellow-500">DHL</span></div></section>
  <section id="solutions" className="bg-[#020d2b] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-6xl"><div className="grid gap-8 lg:grid-cols-[1.1fr_2fr]"><SectionTitle eyebrow="WHAT IS EASY LANE?" title={<>Built to Simplify<br />Complex <span className="text-[#1260ff]">Logistics</span><br />Operations</>} description="" /><div className="grid gap-6 sm:grid-cols-3">{[['Fragmented Operations','Different systems for fleet, finance, drivers and vendors create delays, errors and high operational costs.', Zap],['One Intelligent Platform','Easy Lane centralizes your logistics, finance and operations into an AI-enabled ecosystem.', Bot],['Real Business Impact','Improve visibility, reduce costs, accelerate cash flow and deliver exceptional operational performance.', BarChart3]].map(([title, description, icon]) => <FeatureCard key={title} title={title} description={description} icon={icon} />)}</div></div><div className="mt-10 h-14 rounded-full bg-[radial-gradient(ellipse_at_center,_rgba(24,91,255,.7),transparent_62%)]" /></div></section>
  <section className="mx-auto -mt-1 max-w-6xl rounded-b-3xl border border-slate-100 bg-white px-5 py-12 shadow-sm sm:px-8"><SectionTitle eyebrow="PLATFORM ECOSYSTEM" title="Dedicated Experience for Every Stakeholder" /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{platforms.map((item) => <PlatformCard key={item[0]} item={item} />)}</div></section>
  <section id="services" className="mx-auto grid max-w-6xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><SectionTitle eyebrow="BILL DISCOUNTING" title={<>Faster Payments.<br />Stronger <span className="text-[#1260ff]">Cash Flow.</span></>} description="Convert your unpaid invoices into instant working capital and keep your operations moving without cash flow delays." /><div className="mt-7 grid grid-cols-3 gap-3">{[['Instant Liquidity', Zap],['Risk Protected', ShieldCheck],['Flexible & Simple', Radar]].map(([text, Icon]) => <div key={text}><Icon className="text-[#1260ff]" size={25}/><p className="mt-2 text-xs font-bold">{text}</p><p className="mt-1 text-[10px] text-slate-500">Get funds in as fast as 24 hours</p></div>)}</div></div><motion.div {...fadeUp} className="rounded-[26px] bg-gradient-to-br from-[#f4f8ff] to-[#edf4ff] p-6"><div className="grid items-center gap-4 sm:grid-cols-3"><div className="rounded-lg bg-white p-4 shadow-sm"><p className="text-xs font-bold">INVOICE</p><p className="mt-7 text-[10px] text-slate-400">Invoice Amount</p><p className="font-bold">₹12,50,000</p><span className="mt-4 inline-block rounded bg-emerald-50 px-2 py-1 text-[10px] text-emerald-600">● Approved</span></div><div className="text-center text-[#1260ff]"><CircleDollarSign className="mx-auto"/><ArrowRight className="mx-auto mt-2" /></div><div className="rounded-lg bg-[#041333] p-5 text-white shadow-xl"><p className="text-[10px] text-white/60">FUNDS RECEIVED</p><p className="mt-2 text-xl font-bold">₹11,25,000</p><p className="mt-3 text-[10px] text-emerald-300">90% of invoice value</p></div></div><div className="mt-5 rounded-xl bg-white p-4 text-sm font-semibold text-slate-700">You Save Up To <span className="text-lg text-[#1260ff]">₹1,25,000</span> vs traditional financing</div></motion.div></section>
  <section className="mx-auto max-w-6xl px-5 pb-20 sm:px-8"><SectionTitle eyebrow="HOW IT WORKS" title="From Invoice to Cash in 4 Simple Steps" /><div className="mt-10 grid gap-5 md:grid-cols-4">{steps.map(([number,title,desc,Icon], index) => <motion.div {...fadeUp} key={title} className="relative text-center"><span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-[#1260ff] text-[10px] font-bold text-white">{number}</span>{index < 3 && <span className="absolute left-[60%] top-2.5 hidden h-px w-[80%] border-t border-dotted border-[#1260ff] md:block"/>}<div className="mx-auto mt-5 flex h-16 w-16 items-center justify-center rounded-2xl border border-slate-100 bg-white text-[#1260ff] shadow-md"><Icon size={27}/></div><h3 className="mt-4 text-sm font-bold">{title}</h3><p className="mx-auto mt-2 max-w-40 text-[11px] leading-4 text-slate-500">{desc}</p></motion.div>)}</div></section>
  <section className="mx-auto grid max-w-6xl gap-8 px-5 pb-20 sm:px-8 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><SectionTitle eyebrow="COMPREHENSIVE DASHBOARD" title={<>One Dashboard.<br />Complete Operational<br />Visibility.</>} description="Monitor everything that matters with real-time insights and AI-powered analytics." /><a href="#contact" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#1260ff]">Explore all modules <ArrowRight size={13}/></a></div><DashboardPreview /></section>
  <section className="bg-[#020d2b] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="AI-POWERED TMS" title="Intelligence Built Into Every Operation" /><div className="mt-8 grid gap-4 sm:grid-cols-3 lg:grid-cols-6">{aiItems.map(([title, desc, Icon]) => <motion.div {...fadeUp} key={title} className="border-l border-white/10 pl-3"><Icon className="text-[#1260ff]" size={23}/><h3 className="mt-4 text-xs font-bold">{title}</h3><p className="mt-1 text-[10px] leading-4 text-white/55">{desc}</p></motion.div>)}</div><div className="mt-14 grid gap-7 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><SectionTitle eyebrow="CONTROL TOWER" title="Your Logistics Command Center" description="Monitor your entire logistics network in real-time. Detect delays, manage exceptions and take faster decisions." /><Button href="#contact" className="mt-6 h-10 px-4 text-xs">Explore Control Tower</Button></div><div className="relative"><DashboardPreview dark /><div className="absolute left-[32%] top-[43%] h-2 w-2 rounded-full bg-yellow-300 shadow-[0_0_22px_8px_rgba(250,204,21,.5)]" /></div></div></div></section>
  <section className="mx-auto grid max-w-6xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-2"><div><SectionTitle eyebrow="INDUSTRY SOLUTIONS" title="Solutions for Every Industry" /><div className="mt-7 grid grid-cols-3 gap-6 text-center text-xs font-semibold text-slate-600">{[['FMCG', Boxes],['Retail', BriefcaseBusiness],['Manufacturing', Truck],['Pharma', ShieldCheck],['Cold Chain', Clock3],['3PL & Aggregators', UsersRound]].map(([text,Icon]) => <div key={text}><Icon className="mx-auto mb-2 text-slate-500" size={21}/>{text}</div>)}</div></div><div><SectionTitle eyebrow="TRUSTED BY LEADING BUSINESSES" title="Driving Real Business Results" /><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['23%','Reduction in Operational Delays'],['18%','Fuel Cost Savings'],['40%','Faster Invoice Processing'],['99.9%','Tracking Uptime']].map(([num,label]) => <div key={num} className="rounded-lg border border-slate-100 p-3 text-center shadow-sm"><strong className="text-xl text-[#1260ff]">{num}</strong><p className="mt-1 text-[9px] leading-3 text-slate-500">{label}</p></div>)}</div></div></section>
  <section id="contact" className="bg-gradient-to-r from-[#124dff] to-[#0744e7] px-5 py-6 text-white"><div className="mx-auto flex max-w-6xl flex-col gap-5 text-center sm:flex-row sm:items-center sm:justify-between sm:text-left"><div><h2 className="text-xl font-bold">Ready to Transform Your Logistics Operations?</h2><p className="mt-1 text-xs text-white/80">Join hundreds of businesses moving smarter, faster and better with Easy Lane.</p></div><div className="flex justify-center gap-3"><Button href="#home" className="h-10 px-5 text-xs">Book a Demo</Button><Button href="#home" variant="secondary" className="h-10 px-5 text-xs">Talk to Sales</Button></div></div></section>
</main><Footer /></div>;

export default Home;
